[package]
name = "riptide-syntax"
version = "0.2.0"
authors = ["Stephen M. Coakley <me@stephencoakley.com>"]
description = "The Riptide language parser"
edition = "2018"

[dependencies]
pest = "2.1"
pest_derive = "2.1"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies]
difference = "2.0"
glob = "0.3"
log = "0.4"
ron = "0.5"
stderrlog = "0.4"
toml = "0.5"
